### PR TITLE
Update Bengali translations

### PR DESCRIPTION
**Pull request by AsmSafone**

### CODE REVIEW

**Comment by rojserbest** [comment]
Can you set the commit message to "Update Bengali translations"?

**Comment by AsmSafone** [comment]
> Can you set the commit message to "Update Bengali translations"?

ok. done

**Comment by rojserbest** [comment]
> > Can you set the commit message to "Update Bengali translations"?
> 
> ok. done

"Updated Bengali translations"

I didn't mean the PR title, I meant your commit message. And please remove the older commit with a force push.

**Comment by AsmSafone** [comment]
ok

**Pull request closed without merging**
